apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-deployment
  labels:
    app: converter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
      - name: converter
        image: microservice-converter
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 1323
        envFrom:
        - configMapRef:
            name: converter-configmap-v1
