apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-configmap
data:
  RABBIT_MQ_URL: amqp://guest:guest@host.minikube.internal:5672
  AUDIO_QUEUE: audios
  SMTP_HOST: smtp.freesmtpservers.com
  SMTP_PORT: "25"
  FROM_EMAIL: no-reply@microservice.com
  DOWNLOAD_HOST: http://localhost:1324
  